# Generated by Django 3.2.13 on 2025-11-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_add_telefono_to_user'),
        ('api_user', '0004_add_telefono_to_user'),
    ]

    operations = [
    ]
