"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Try to use `django-environ` when available; fall back to a minimal env() helper
try:
    import environ

    env = environ.Env(
        # set casting, default value
        DEBUG=(bool, False)
    )
except Exception:
    def env(key, default=None):
        return os.environ.get(key, default)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="insecure-S#perS3crEt_007")

# Production: disable debug by default. Use environment variables to enable only when needed.
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS", default="localhost 127.0.0.1 0.0.0.0").split(" ")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "api",
    "api.user",
    "api.authentication",
    "api.clinic.apps.ClinicConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # "whitenoise.middleware.WhiteNoiseMiddleware",  # Uncomment for production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.postgresql'),
        # AQUÍ ESTABA EL ERROR: Cambiamos 'DB_DATABASE' por 'DB_NAME'
        'NAME': env('DB_NAME', default='mi_base_datos'),
        'USER': env('DB_USER', default='usuario_admin'),
        'PASSWORD': env('DB_PASSWORD', default='16C5313UXXF'),
        'HOST': env('DB_HOST', default='db-postgres'),
        'PORT': env('DB_PORT', default='5432'),
    }
}
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Root folder where `collectstatic` will gather static files for production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Uncomment for production:
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user Model
AUTH_USER_MODEL = "api_user.User"

# ##################################################################### #
# ################### REST FRAMEWORK             ###################### #
# ##################################################################### #

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "api.authentication.backends.ActiveSessionAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    # drf-spectacular schema class
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "React Soft Dashboard Django API",
    "DESCRIPTION": "OpenAPI schema for the Django backend used by the React soft dashboard.",
    "VERSION": "1.0.0",
    "SERVERS": [{"url": "http://localhost:5000", "description": "Local dev"}],
    # tag order and descriptions shown by Redoc
    "TAGS": [
        {"name": "Auth", "description": "Endpoints de autenticación: login, registro y tokens"},
        {"name": "Usuarios", "description": "Operaciones sobre usuarios (perfil, creación administrativa)"},
        {"name": "Dueños", "description": "Crear, actualizar y listar dueños y su información"},
        {"name": "Recepcionistas", "description": "Gestión de recepcionistas (admin)"},
        {"name": "Veterinarios", "description": "Gestión de veterinarios y su perfil"},
        {"name": "Mascotas", "description": "Operaciones sobre mascotas y listas por dueño"},
        {"name": "Consultas", "description": "Consultas médicas y reservas (unificadas)"},
        {"name": "Perfil", "description": "Endpoints para obtener/editar el perfil autenticado"},
    ],
}

# Static files dirs so our custom redoc assets are found in DEBUG
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Optional OpenAPI extras for a nicer docs page
SPECTACULAR_SETTINGS.update({
    "CONTACT": {"name": "API Support", "email": "support@example.com"},
    "LICENSE": {"name": "MIT", "url": "https://opensource.org/licenses/MIT"},
})

# ##################################################################### #
#  CORS 
# ##################################################################### #

CORS_ALLOW_ALL_ORIGINS=True

# Load the default ones
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]

# Leaded from Environment
CORS_ALLOWED_ORIGINS_ENV = env("CORS_ALLOWED_ORIGINS", default=None)

if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS += CORS_ALLOWED_ORIGINS_ENV.split(' ')


# ##################################################################### #
#  TESTING 
# ##################################################################### #

TESTING = False
TEST_RUNNER = "core.test_runner.CoreTestRunner"
