# Generated by Django 3.2.13 on 2025-11-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('idDueno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('idRecepcionista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('idVeterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=100)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='api_clinic.dueno')),
                ('registrada_por_recepcionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_registradas', to='api_clinic.recepcionista')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api_clinic.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='dueno',
            name='registrado_por_recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duenos_registrados', to='api_clinic.recepcionista'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api_clinic.historial')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='api_clinic.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('idCom', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='api_clinic.cita')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='api_clinic.dueno')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api_clinic.dueno'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='api_clinic.veterinario'),
        ),
    ]
