# Generated by Django 3.2.13 on 2025-12-08 11:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('idDueno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('idVeterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('work_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('work_end', models.TimeField(blank=True, default=datetime.time(14, 0), null=True)),
                ('work_days', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinario_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('idRecepcionista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=100)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='api_clinic.dueno')),
                ('registrada_por_recepcionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_registradas', to='api_clinic.recepcionista')),
            ],
        ),
        migrations.AddField(
            model_name='dueno',
            name='registrado_por_recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duenos_registrados', to='api_clinic.recepcionista'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('asistio', models.BooleanField(blank=True, default=None, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api_clinic.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='api_clinic.veterinario')),
            ],
        ),
    ]
