# Generated by assistant - add nombre fields to Dueno and Recepcionista
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_clinic", "0003_alter_recepcionista_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recepcionista",
            name="nombre",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="dueno",
            name="nombre",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
