# Generated by assistant - add OneToOneField user to Veterinario
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_clinic", "0004_add_nombre_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinario",
            name="user",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinario_profile', to='api_user.user'),
        ),
    ]
