# Generated by Django 3.2.13 on 2025-11-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_clinic', '0008_add_mascota_to_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api_clinic.dueno'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
