# Generated by Django 3.2.13 on 2025-11-25 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_clinic', '0012_delete_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='work_end',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), null=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='work_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('idCom', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='api_clinic.consulta')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='api_clinic.dueno')),
            ],
        ),
    ]
