# Generated by Django 3.2.13 on 2025-11-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_clinic', '0014_remove_dueno_user_and_simplify_consulta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
