# Generated by Django 3.2.13 on 2025-12-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_clinic', '0016_add_asistio_to_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='asistio',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
